### ISSUE TITLE
can't run the example

### ISSUE THREAD

**Issue by Donih** [csurfer/rake-nltk#13]
when I run this 
`from rake_nltk import Rake

r = Rake() # Uses stopwords for english from NLTK, and all puntuation characters.

text = '''Compatibility of systems of linear constraints over the set of
        natural numbers. Criteria of compatibility of a system of linear
        Diophantine equations, strict inequations, and nonstrict inequations are
        considered. Upper bounds for components of a minimal set of solutions
        and algorithms of construction of minimal generating sets of solutions
        for all types of systems are given. These criteria and the corresponding
        algorithms for constructing a minimal supporting set of solutions can be
        used in solving all the considered types of systems and systems of mixed
        types.'''
r.extract_keywords_from_text(text)
r.get_ranked_phrases()`

I get this result:
`Traceback (most recent call last):
  File "/Users/donya/PycharmProjects/test/test.py", line 20, in <module>
    r.extract_keywords_from_text(text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rake_nltk/rake.py", line 66, in extract_keywords_from_text
    self.extract_keywords_from_sentences(sentences)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rake_nltk/rake.py", line 74, in extract_keywords_from_sentences
    phrase_list = self._generate_phrases(sentences)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rake_nltk/rake.py", line 172, in _generate_phrases
    word_list = [word.lower() for word in wordpunct_tokenize(sentence)]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/tokenize/regexp.py", line 126, in tokenize
    self._check_regexp()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/tokenize/regexp.py", line 121, in _check_regexp
    self._regexp = compile_regexp_to_noncapturing(self._pattern, self._flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/internals.py", line 56, in compile_regexp_to_noncapturing
    return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.parse(pattern)), flags=flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/internals.py", line 52, in convert_regexp_to_noncapturing_parsed
    parsed_pattern.pattern.groups = 1
AttributeError: can't set attribute`
I am new to python. Please  help me
Thanks

**Comment by djack-techpats** [comment]
It's been awhile since I've used this but the way it was working for me was: 
 
text = open('text.txt','r').read()
rake = Rake("SmartStoplist.txt",3,4,1)
keywords = rake.run(text)

I'm not familiar enough with Python yet myself to debug your Traceback.

**Comment by csurfer** [comment]
Looks like an issue with nltk https://github.com/nltk/nltk/issues/1106. Try installing your nltk package again and check.
