### ISSUE TITLE
Installation fails on Google App Engine

### ISSUE THREAD

**Issue by oli666** [csurfer/rake-nltk#43]
I am using the followign requirements to install to Google App Engine: 

nltk==3.4.5
rake-nltk==1.0.4

The deployment fails with the error messages below; I can, however, deploy nltk 3.4.5 without any issues. Only the post installation tasks of rake-nltk seem to be the issues. 

Step #1 - "builder":   Copying rake_nltk.egg-info to build/bdist.linux-x86_64/wheel/rake_nltk-1.0.4-py3.7.egg-info
Step #1 - "builder":   running install_scripts
Step #1 - "builder":   Running post installation tasks
Step #1 - "builder":   Traceback (most recent call last):
Step #1 - "builder":     File "<string>", line 1, in <module>
Step #1 - "builder":     File "/tmp/pip-wheel-bw7rzw5o/rake-nltk/setup.py", line 81, in <module>
Step #1 - "builder":       cmdclass={"develop": PostDevelop, "install": PostInstall},
Step #1 - "builder":     File "/env/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
Step #1 - "builder":       return distutils.core.setup(**attrs)
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/core.py", line 148, in setup
Step #1 - "builder":       dist.run_commands()
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
Step #1 - "builder":       self.run_command(cmd)
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1 - "builder":       cmd_obj.run()
Step #1 - "builder":     File "/env/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 259, in run
Step #1 - "builder":       self.run_command('install')
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
Step #1 - "builder":       self.distribution.run_command(command)
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1 - "builder":       cmd_obj.run()
Step #1 - "builder":     File "/tmp/pip-wheel-bw7rzw5o/rake-nltk/setup.py", line 36, in run
Step #1 - "builder":       self.execute(_post_install, [], msg="Running post installation tasks")
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 335, in execute
Step #1 - "builder":       util.execute(func, args, msg, dry_run=self.dry_run)
Step #1 - "builder":     File "/opt/python3.7/lib/python3.7/distutils/util.py", line 291, in execute
Step #1 - "builder":       func(*args)
Step #1 - "builder":     File "/tmp/pip-wheel-bw7rzw5o/rake-nltk/setup.py", line 17, in _post_install
Step #1 - "builder":       import nltk
Step #1 - "builder":   ModuleNotFoundError: No module named 'nltk'
Step #1 - "builder":   ----------------------------------------
Step #1 - "builder":   ERROR: Failed building wheel for rake-nltk
Step #1 - "builder": ERROR: Failed to build one or more wheels

**Comment by csurfer** [comment]
@oli666 From the error you have posted above

```
Step #1 - "builder": ModuleNotFoundError: No module named 'nltk'
Step #1 - "builder": ----------------------------------------
Step #1 - "builder": ERROR: Failed building wheel for rake-nltk
Step #1 - "builder": ERROR: Failed to build one or more wheels
```

it looks like when we try to access nltk library from within rake-nltk we are not able to find it. Can you check the installation path within your app-engine setup and see if there is any path issues.
